#+ endpoint: https://sparql.rhea-db.org/sparql
#+ summary: Select the number of reactions with no links to EC numbers
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rh:<http://rdf.rhea-db.org/>
SELECT
  (count(?reaction) as ?reactionCount)
WHERE {
  ?reaction rdfs:subClassOf rh:Reaction .
  FILTER (NOT EXISTS {?reaction rh:ec ?ecNumber .})
}
