#+ endpoint: https://sparql.rhea-db.org/sparql
#+ summary: Select all Rhea reactions annotated with a given Pubmed ID
PREFIX pubmed: <http://rdf.ncbi.nlm.nih.gov/pubmed/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rh: <http://rdf.rhea-db.org/>

# Query 2 
# Select all Rhea reactions annotated with a given Pubmed identifier (PMID = 29867142)
#
SELECT ?pubmed ?rhea ?accession ?isTransport  ?equation 
WHERE {
  ?rhea rdfs:subClassOf rh:Reaction .
  ?rhea rh:accession ?accession .
  ?rhea rh:citation ?pubmed .
  VALUES (?pubmed) { (pubmed:29867142) }
  ?rhea rh:isTransport ?isTransport .
  ?rhea rh:equation ?equation .
} ORDER BY ?rhea
