#+ endpoint: https://sparql.rhea-db.org/sparql/
#+ summary: Select the fifth to fiftheenth (inclusive) reactions, with the lowest identifier by alphabetic sort
PREFIX rh:<http://rdf.rhea-db.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?reaction ?reactionId WHERE {
  ?reaction rdfs:subClassOf rh:Reaction .
  ?reaction rh:id ?reactionId . 
}
ORDER BY ?reaction
LIMIT 10
OFFSET 5
