#+ endpoint: https://sparql.rhea-db.org/sparql/
#+ summary: Select all approved reactions linked to PMID:2460092
PREFIX rh:<http://rdf.rhea-db.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pubmed:<http://rdf.ncbi.nlm.nih.gov/pubmed/>

SELECT ?reaction ?reactionEquation  WHERE {
  BIND(pubmed:2460092 AS ?cit)
  ?reaction rdfs:subClassOf rh:Reaction .
  ?reaction rh:status rh:Approved .
  ?reaction rh:equation ?reactionEquation .
  ?reaction rh:citation ?cit .
}
ORDER BY ?reaction
