#+ endpoint: https://sparql.rhea-db.org/sparql/
#+ summary: Select all approved reactions annotated with a given Pubmed ID (2460092, and show the pubmed id in result as text, using strafter and BIND)
PREFIX rh:<http://rdf.rhea-db.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pubmed:<http://rdf.ncbi.nlm.nih.gov/pubmed/>

SELECT ?reaction ?pubMedID ?reactionEquation  WHERE {
  BIND(pubmed:2460092 AS ?cit)
  ?reaction rdfs:subClassOf rh:Reaction .
  ?reaction rh:status rh:Approved .
  ?reaction rh:equation ?reactionEquation .
  ?reaction rh:citation ?cit .
  BIND(strafter(str(?cit), str(pubmed:)) AS ?pubMedID  )
}
