#+ endpoint: https://sparql.rhea-db.org/sparql
#+ summary: Select all the descendants of CHEBI:35179 (a 2-oxo carboxylate) in the ChEBI hierarchy (using rdfs:subClassOf+), used in Rhea reaction or not
PREFIX CHEBI: <http://purl.obolibrary.org/obo/CHEBI_>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rh:<http://rdf.rhea-db.org/>
SELECT
  ?chebiDescendant
  (str(?label) as ?chebiDescendantName)
WHERE {
  ?chebiDescendant rdfs:subClassOf+ CHEBI:35179 .
  ?chebiDescendant rdfs:label ?label .
}
ORDER BY ?chebiDescendant
