#+ endpoint: https://sparql.rhea-db.org/sparql
#+ summary: How many reactions involve CHEBI:17815 (a 1,2-diacyl-sn-glycerol) or one of its descendant?
PREFIX CHEBI: <http://purl.obolibrary.org/obo/CHEBI_>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rh:<http://rdf.rhea-db.org/>

SELECT
  (count(distinct ?reaction) as ?countReaction)
WHERE {
  ?reaction rdfs:subClassOf rh:Reaction ;
  rh:status rh:Approved ;
    rh:side ?reactionSide .

  ?reactionSide rh:contains ?participant .
  ?participant rh:compound ?compound .
  ?compound rh:chebi ?chebi .
  ?chebi rdfs:subClassOf* CHEBI:17815 .
}
