#+ endpoint: https://sparql.rhea-db.org/sparql
#+ summary: Get structural data of a given ChEBI compound (CHEBI:29985 L-glutamate)
#
# get structural data of a given ChEBI compound
#
PREFIX rh:<http://rdf.rhea-db.org/>
PREFIX CHEBI:<http://purl.obolibrary.org/obo/CHEBI_>
PREFIX chebihash:<http://purl.obolibrary.org/obo/chebi/>
SELECT
  ?chebi
  ?formula
  ?charge
  ?mass
  ?monoisotopicmass
  ?inchikey
  ?smiles
  ?inchi
WHERE {
  BIND (CHEBI:29985 AS ?chebi)
  ?chebi chebihash:inchi ?inchi ;
    chebihash:smiles ?smiles ;
    chebihash:formula ?formula ;
    chebihash:mass ?mass ;
    chebihash:charge ?charge ;
    chebihash:inchikey ?inchikey ;
    chebihash:monoisotopicmass ?monoisotopicmass .
}
