#+ endpoint: https://sparql.orthodb.org/sparql/
#+ summary: Find all OrthoDB species with attached OrthoDB organisms containing "drosophila" in the beginning of the taxonomic name
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX : <http://purl.orthodb.org/>

SELECT *
WHERE {
    ?tx a :Species; up:scientificName ?tax_name .
    ?org a ?tx; up:scientificName ?org_name.
    FILTER(strstarts (lcase(?tax_name ), "drosophila" ))
}
