#+ endpoint: https://sparql.uniprot.org/sparql/
#+ summary: The recommended protein full names for UniProtKB entries
#+ tags:
#+ - protein name
PREFIX up: <http://purl.uniprot.org/core/>

SELECT ?protein
  ?fullName
WHERE {
  ?protein a up:Protein ;
           up:recommendedName ?recommendedName .
  ?recommendedName up:fullName ?fullName .
}
