#+ endpoint: https://sparql.uniprot.org/sparql/
#+ summary: Was any UniProtKB entry integrated on the 9th of January 2013
#+ tags:
#+ - date
#+ - entry history
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

ASK
WHERE
{
	?protein a up:Protein .
	?protein up:created '2013-01-09'^^xsd:date
}
