#+ endpoint: https://sparql.uniprot.org/sparql/
#+ summary: Translate the global unique identifier for a UniProtKB record into other options using the bioregistry translating endpoint.
#+ tags:
#+ - identifier
#+ - mapping
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX uniprotkb: <http://purl.uniprot.org/uniprot/>
PREFIX up: <http://purl.uniprot.org/core/>

SELECT 
    ?protein 
    ?otherIdentifier
WHERE {
    BIND(uniprotkb:P00750 AS ?protein)
    ?protein a up:Protein .
    SERVICE <https://bioregistry.io/sparql> {
        ?protein owl:sameAs ?otherIdentifier .
    }
}
