#+ endpoint: https://sparql.uniprot.org/sparql/
#+ summary: List UniProtKB proteins with their associated gene and the gene's names that are used in the field, but not recommended for use by UniProtKB
#+ tags:
#+ - gene name
#+ - list
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX up: <http://purl.uniprot.org/core/>

SELECT ?protein
  ?gene ?altGeneName
WHERE {
  ?protein a up:Protein ;
           up:encodedBy ?gene .
  ?gene skos:altLabel ?altGeneName .
}
