#+ endpoint: https://sparql.cellosaurus.org/sparql
#+ summary: Direct and indirect parent cell lines from which some cell line originates
#+ tags:
#+ - hi
#+ - parent
PREFIX cello: <https://purl.expasy.org/cellosaurus/rdf/ontology/>
PREFIX cvcl: <https://purl.expasy.org/cellosaurus/rdf/cvcl/>
select ?cl ?cl_name ?parent_cl ?parent_cl_name where {
  values ?cl {	cvcl:CVCL_D5AX }
  ?cl cello:recommendedName ?cl_name .
  ?cl cello:hasParentCellLine+ ?parent_cl .
  ?parent_cl cello:recommendedName ?parent_cl_name .
}
order by ?cl
limit 100
