#+ endpoint: https://www.bgee.org/sparql/
#+ summary: What are the anatomical entities where the APOC1 Homo sapiens gene is not expressed, that is where is APOC1 absent?
PREFIX genex: <http://purl.org/genex#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX orth: <http://purl.org/net/orth#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX up: <http://purl.uniprot.org/core/>

SELECT DISTINCT ?anat ?anatName WHERE {
    ?seq a orth:Gene ;
        rdfs:label "APOC1" ;
        genex:isAbsentIn ?anat ;
        orth:organism ?organism .
    ?anat a genex:AnatomicalEntity ;
        rdfs:label ?anatName .
    ?organism obo:RO_0002162  ?species .
    ?species a up:Taxon ;
        up:scientificName "Homo sapiens" .
}
