#+ endpoint: https://www.bgee.org/sparql/
#+ summary: What is the post-juvenile stage link and description?
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX efo: <http://www.ebi.ac.uk/efo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?stage ?stageName ?stageDescription WHERE {
    ?stage a efo:EFO_0000399 ;
        rdfs:label ?stageName ;
        dcterms:description ?stageDescription .
    FILTER(CONTAINS(LCASE(?stageName), "post-juvenile"))
}
