#+ endpoint: https://rdf.metanetx.org/sparql/
#+ summary: For the KEGG compound C01732, retrieve the MNXref identifier, name and reference
PREFIX keggC: <https://identifiers.org/kegg.compound:>
PREFIX mnx: <https://rdf.metanetx.org/schema/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# For the KEGG compound *C01732*, retrieve the MNXref
# identifier, name and reference.

SELECT ?metabolite ?reference ?name
WHERE {
    ?metabolite a mnx:CHEM .
    ?metabolite mnx:chemRefer ?reference .
    ?metabolite rdfs:comment ?name .
    ?metabolite mnx:chemXref keggC:C01732
}
