#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with a localization keyword that do not have the corresponding subcellular location annotation and/or GO cellular component annotatio
#+ tags:
#+ - QC
#+ - cellular component
#+ - keyword
#+ - subcellular location
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>

select distinct ?entry ?kw ?subcell ?gocc where {
  ?entry :isoform /:keyword /:term ?kw.
  ?subcell a :UniprotSubcellularLocationCv.
  ?kw :related ?subcell.
  ?gocc a :GoCellularComponentCv.
  ?kw :related ?gocc.
  ?entry :isoform /:goCellularComponent ?comp.
  filter not exists {?comp :negativeEvidence ?negev} # No negative evidence
  filter not exists {?comp :term ?gocc.}
  ?entry :isoform /:subcellularLocation ?comp.
  filter not exists {?comp :negativeEvidence ?negev} # No negative evidence
  filter not exists {?comp :term ?gocc.}
}
