#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with topological domain annotations with evidence from UniProt that is negative
#+ tags:
#+ - QC
#+ - evidence
#+ - negative
#+ - sequence
#+ - topology
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform /:topologicalDomain /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
