#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Proteins that are glycosylated and are not located in the membrane
#+ tags:
#+ - PTM
#+ - glycosylation
#+ - subcellular location
#+ - tutorial
PREFIX : <http://nextprot.org/rdf/>
PREFIX nextprot_cv: <http://nextprot.org/rdf/terminology/>

SELECT DISTINCT ?entry WHERE {
 ?entry :isoform ?iso.
 ?iso :uniprotKeyword / :term nextprot_cv:KW-0325.
 filter not exists { ?iso :uniprotKeyword / :term nextprot_cv:KW-0812.} # KW for Transmembrane
 filter not exists { ?iso :topology / :term nextprot_cv:CVTO_0004 } # intramembrane segment
}
