#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with domain annotations with evidence NOT from UniProt
#+ tags:
#+ - QC
#+ - domain
#+ - provenance
#+ - sequence
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :domain /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
