#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Proteins with a protein existence "At transcript level" (PE=2)
#+ tags:
#+ - protein existence
#+ - tutorial
PREFIX : <http://nextprot.org/rdf/>

SELECT DISTINCT ?entry WHERE {
 ?entry :existence :Evidence_at_transcript_level
}
