#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with GO biological process annotations with the evidence code is ND (ECO:0000035)
#+ tags:
#+ - QC
#+ - evidence
#+ - filtering
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :goBiologicalProcess /:evidence /:evidenceCode cv:ECO_0000035.
}
