#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with temperature dependence annotations with evidence from Uniprot of quality SILVER
#+ tags:
#+ - QC
#+ - enzyme
#+ - evidence
#+ - function
#+ - quality
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform /:temperatureDependence /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
