#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Proteins with at least one HPA antibody that are located in the peroxisome
#+ tags:
#+ - antibody
#+ - subcellular location
#+ - tutorial
PREFIX : <http://nextprot.org/rdf/>
PREFIX nextprot_cv: <http://nextprot.org/rdf/terminology/>

SELECT DISTINCT ?entry WHERE {
 values ?peroxiloc {nextprot_cv:GO_0005777 nextprot_cv:SL-0204} # GO and SL values for peroxisome

 ?entry :isoform ?iso.
 ?iso :antibodyMapping ?map.
 ?iso :cellularComponent ?loc .
 ?loc :term /:childOf ?peroxiloc. # peroxisomal
 filter not exists { ?loc :negativeEvidence ?negev. } # No negative localization evidence
}
