#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with phenotypic variation annotations with evidence NOT from neXtProt
#+ tags:
#+ - QC
#+ - phenotype
#+ - provenance
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :proteoform /:phenotypicVariation /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:NextProt))
}
