#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Recommended isoform names for MSH6
#+ tags:
#+ - isoforms
#+ - tutorial
PREFIX : <http://nextprot.org/rdf/>
PREFIX nextprot: <http://nextprot.org/rdf/entry/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?iso ?name WHERE {
 nextprot:NX_P52701 :isoform ?iso. # MSH6 entry
 ?iso :recommendedName ?name_entity .
 ?name_entity a :IsoformName; rdfs:label ?name.
}
order by asc(?iso)
