#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with PDB mapping annotations with evidence from UniProt that is negative
#+ tags:
#+ - 3D structure
#+ - QC
#+ - evidence
#+ - negative
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform /:pdbMapping /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
