#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Proteins with at least one known SUMOylation site
#+ tags:
#+ - PTM
#+ - tutorial
PREFIX : <http://nextprot.org/rdf/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entry WHERE {
 ?entry :isoform ?iso.
 ?iso :crossLink /rdfs:comment ?comment.
 filter(contains (?comment,'SUMO'))
}
