#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with transport activity annotations from TCDB for which the evidence code is NOT curator inference used in manual assertion
#+ tags:
#+ - ECO
#+ - QC
#+ - evidence
#+ - function
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry  where {
  ?entry :isoform /:transportActivity /:evidence ?ev1.
  ?ev1 :assignedBy source:TCDB.
  ?ev1 :evidenceCode ?eco.
  filter (?eco not in (cv:ECO_0000305))
}
