#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Proteins that are located in the mitochondrion with an experimental evidence originating not from HPA or DKFZ-GFP
#+ tags:
#+ - method
#+ - subcellular location
#+ - tutorial
PREFIX : <http://nextprot.org/rdf/>
PREFIX nextprot_cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

SELECT DISTINCT ?entry WHERE {
 values ?mitoloc {nextprot_cv:SL-0173 nextprot_cv:GO_0005739} # SL and GO values for mitochondrion

 ?entry :isoform ?iso.
 ?iso :cellularComponent ?loc.
 ?loc :term /:childOf ?mitoloc.
 filter not exists { ?loc :negativeEvidence ?negev. } # No negative localization evidence
 ?loc :evidence /:assignedBy ?src.
 filter ( ?src not in (source:Human_protein_atlas, source:GFP-cDNAEMBL))
}
