#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with expression profile annotations with evidence NOT from Bgee or HPA
#+ tags:
#+ - QC
#+ - provenance
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :expressionProfile /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Bgee, source:Human_protein_atlas))
}
