#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with transport activity annotations with evidence from TCDB of quality SILVER
#+ tags:
#+ - QC
#+ - evidence
#+ - function
#+ - quality
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform /:transportActivity /:evidence ?ev1.
  ?ev1 :assignedBy source:TCDB.
  ?ev1 :quality :SILVER.
}
