#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with beta strand annotations with evidence NOT from UniProt
#+ tags:
#+ - QC
#+ - provenance
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :betaStrand /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot))
}
