#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with GO molecular function annotations with evidence from ENSEMBL of quality GOLD
#+ tags:
#+ - QC
#+ - evidence
#+ - function
#+ - quality
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform /:goMolecularFunction /:evidence ?ev1.
  ?ev1 :assignedBy source:Ensembl.
  ?ev1 :quality :GOLD.
}
