#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Proteins located in the mitochondrion and which are enzymes
#+ tags:
#+ - enzyme
#+ - function
#+ - subcellular location
#+ - tutorial
PREFIX : <http://nextprot.org/rdf/>
PREFIX nextprot_cv: <http://nextprot.org/rdf/terminology/>

SELECT DISTINCT ?entry WHERE {
 values ?mitoloc {nextprot_cv:SL-0173 nextprot_cv:GO_0005739} # SL and GO values for mitochondrion
 ?entry :isoform / :enzymeClassification ?_ .
 ?entry :isoform ?iso.
 ?iso :cellularComponent ?loc .
 ?loc :term / :childOf ?mitoloc.
 filter not exists { ?loc :negativeEvidence ?negev. } # No negative localization evidence
}
