#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Phosphorylation sites from PeptideAtlas Phosphoproteome
#+ tags:
#+ - dataset
#+ - phosphorylation
#+ - proteomics
#+ - tutorial
PREFIX : <http://nextprot.org/rdf/>
PREFIX source: <http://nextprot.org/rdf/source/>

SELECT DISTINCT (sample(?iso) as ?isospl) (sample(?pos) as ?posspl) WHERE {
 ?entry :isoform ?iso .
 ?iso :ptm ?ptm.
 ?ptm :entryAnnotationId ?ptmid; :start ?pos .
 ?ptm :evidence / :assignedBy source:PeptideAtlas_human_phosphoproteome .
}
group by ?ptmid
order by ?isospl ?posspl
