#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with antibody mapping annotations with evidence from HPA that is negative
#+ tags:
#+ - QC
#+ - antibody
#+ - evidence
#+ - negative
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform /:antibodyMapping /:evidence ?ev.
  ?ev :assignedBy source:Human_protein_atlas.
  ?ev :negative 1.
}
