#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with expression profile annotations from Bgee for which the evidence code is NOT microarray RNA expression level evidence (ECO:0000104), transcript expression evidence (ECO:0000009) or RNA-sequencing evidence (ECO:0000295)
#+ tags:
#+ - ECO
#+ - QC
#+ - evidence
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform /:expressionProfile /:evidence ?ev1.
  ?ev1 :assignedBy source:Bgee.
  ?ev1 :evidenceCode ?eco.
  filter (?eco not in (cv:ECO_0000104, cv:ECO_0000009, cv:ECO_0000295))
}
