#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with glycosylation site annotations from neXtProt for which the evidence code is NOT mass spectrometry evidence
#+ tags:
#+ - ECO
#+ - QC
#+ - evidence
#+ - glycosylation
#+ - sequence
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform /:glycosylationSite /:evidence ?ev1.
  ?ev1 :assignedBy source:NextProt.
  ?ev1 :evidenceCode ?eco.
  filter (?eco not in (cv:ECO_0001096))
}
