#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Proteins that are PE>1 with at least one proteotypic peptide of at least 9 amino-acids identified in a human sample 
#+ tags:
#+ - dataset
#+ - peptide
#+ - protein existence
#+ - proteomics
#+ - tutorial
PREFIX : <http://nextprot.org/rdf/>

SELECT DISTINCT ?entry WHERE {
 values ?level {
 	:Evidence_at_transcript_level # PE=2
 	:Inferred_from_homology 	# PE=3
 	:Predicted 	# PE=4
	:Uncertain 	# PE=5
	}
 ?entry a :Entry .
 ?entry :existence ?level .
 ?entry :isoform / :peptideMapping ?pm.
 ?pm :proteotypic true .
 ?pm :start ?pos1 ; :end ?pos2 .
 filter((?pos2 - ?pos1 + 1) >= 9)
 }
