#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with GO cellular component annotations with the GO qualifier contributes_to
#+ tags:
#+ - QC
#+ - subcellular location
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :goCellularComponent ?gocc.
  ?gocc rdfs:comment ?txt.
  filter (regex(?txt, "^Contributes to"@en))
}
