#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with transport activity annotations with evidence from TCDB that is negative
#+ tags:
#+ - QC
#+ - evidence
#+ - function
#+ - negative
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform /:transportActivity /:evidence ?ev.
  ?ev :assignedBy source:TCDB.
  ?ev :negative 1.
}
