#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no coiled coil region annotations with evidence from UniProt of quality SILVER
#+ tags:
#+ - QC
#+ - evidence
#+ - quality
#+ - region
#+ - sequence
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform /:coiledCoilRegion /:evidence ?ev1.
  ?ev1 :assignedBy source:Uniprot.
  ?ev1 :quality :SILVER.
}
