#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with modified residue phosphorylation site annotations that do not have the keyword Phosphoprotein (KW-0597)
#+ tags:
#+ - QC
#+ - keyword
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>

select distinct ?entry where {  # Include ?phospho if result is not 0 to identify problem site
  ?phospho a :UniprotPtmCv.
  cv:KW-0597 :related  ?phospho.
  ?entry :isoform ?iso.
  ?iso :modifiedResidue ?mod.
  ?mod :term ?phospho.
  filter not exists {?mod :negativeEvidence ?negev} # No negative evidence
  filter not exists {?entry :isoform /:keyword /:term cv:KW-0597.}
}
