#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Proteins with at least one 3D structure of resolution less than 3 Angstroms
#+ tags:
#+ - 3D structure
#+ - tutorial
PREFIX : <http://nextprot.org/rdf/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?entry WHERE {
 ?entry :isoform ?iso.
 ?iso :pdbMapping ?map.
 ?map :resolution ?res_and_unit.
 bind (xsd:float(substr(?res_and_unit,0,strlen(?res_and_unit)-2)) as ?res)
 filter (?res <= 3.0)
}
