#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with an xref to an ENSP but no xref to an ENST
#+ tags:
#+ - QC
#+ - chromosomal location
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX db: <http://nextprot.org/rdf/db/>

select distinct ?entry where {
  ?entry a :Entry.
  filter exists {
    ?entry :reference ?x.
    ?x :provenance db:Ensembl ; :accession ?ac.
    filter (regex(?ac,'^ENSP'))
  }
  filter not exists {
    ?entry :reference ?x.
    ?x :provenance db:Ensembl ; :accession ?ac.
    filter (regex(?ac,'^ENST'))
  }
}
