#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with nucleotide phosphate binding region annotations with evidence from UniProt that is negative
#+ tags:
#+ - QC
#+ - evidence
#+ - interaction
#+ - negative
#+ - region
#+ - sequence
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform /:nucleotidePhosphateBindingRegion /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
