#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with domain information annotations with evidence from UniProt that is negative
#+ tags:
#+ - QC
#+ - evidence
#+ - negative
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform /:domainInfo /:evidence ?ev.
  ?ev :assignedBy source:Uniprot.
  ?ev :negative 1.
}
