#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with GO biological process annotations with evidence from DIBU of the GO Consortium
#+ tags:
#+ - QC
#+ - function
#+ - provenance
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :goBiologicalProcess /:evidence /:assignedBy source:DIBU.
}
