#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with variant annotations with evidence NOT from Cellosaurus, Cosmic, dbSNP, gnomAD, neXtProt or UniProt
#+ tags:
#+ - QC
#+ - provenance
#+ - variant
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :variant /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Cellosaurus,source:Cosmic,source:dbSNP,source:gnomAD,source:NextProt,source:Uniprot))
}
