#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with expression profile annotations with evidence from EST which are NOT from Bgee
#+ tags:
#+ - ECO
#+ - QC
#+ - provenance
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :expressionProfile /:evidence ?ev.
  ?ev :evidenceCode cv:ECO_0000009. # EST
  filter not exists { ?ev :assignedBy source:Bgee }
}
