#+ endpoint: https://sparql.nextprot.org/sparql
#+ summary: Check there are no entries with small molecule interaction annotations with evidence NOT from DrugBank or UniProt
#+ tags:
#+ - QC
#+ - interaction
#+ - provenance
PREFIX : <http://nextprot.org/rdf/>
PREFIX cv: <http://nextprot.org/rdf/terminology/>
PREFIX source: <http://nextprot.org/rdf/source/>

select distinct ?entry ?src where {
  ?entry :isoform ?iso.
  ?iso :smallMoleculeInteraction /:evidence /:assignedBy ?src.
  filter ( ?src not in (source:Uniprot,source:DrugBank))
}
